#!/bin/bash
# Converts RAWs to jpg

#DEBUG="true"
DEBUG="false"

cd "$1"
for k in `ls *.{cr2,CR2} 2>/dev/null`; do
	order="ufraw-batch --wb=camera --exposure=auto --out-type=jpeg --compression=100 --out-path=../ $k"

	if [ "$DEBUG" == "true" ]; then
		echo "$order"
	else
		eval "$order"
	fi
done
